### ISSUE TITLE
Sunny joins the repo

### ISSUE THREAD

**Issue by linyuchin-joey** [linyuchin-joey/joeywk#3]
@earthen7

**Comment by linyuchin-joey** [comment]
1. - [ ] Set up email account in github
2. - [ ] Install app on phone
3. - [ ] Set up "watch" for all activities
4. - [ ] Set up "Start" to subscribe the repo

**Comment by linyuchin-joey** [comment]
@earthen7

**Comment by linyuchin-joey** [comment]
@earthen7 
Pls finish the last task

**Comment by earthen7** [comment]
finish
