### ISSUE TITLE
Sunny to finish the first readme.md

### ISSUE THREAD

**Issue by linyuchin-joey** [linyuchin-joey/joeywk#4]
@earthen7

**Comment by bipu1234** [comment]
Help us

**Comment by linyuchin-joey** [comment]
@earthen7 pls follow the test.md in the tab "code" and create a readme.md with the same contect

**Comment by linyuchin-joey** [comment]
@earthen7 
Please comment on what's your progress today

**Comment by earthen7** [comment]
create readme.md

**Comment by linyuchin-joey** [comment]
Comment on what you get or achieve so far. I'd like to see your progress update and plan the next step for you. Thank you very much!

**Comment by earthen7** [comment]
finish
